config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resource :sessions, only: [:new, :create, :destroy]
  resources :entities, only: [:index, :show]

  resources :users, only: [:create, :new] do
    resources :entities, controller: 'users/entities'
  end

  get 'entities/:id/rides' => 'entities#rides', as: 'rides'
  get 'entities/:id/tickets' => 'entities#tickets', as: 'tickets'
  get 'twitter/latest' => 'twitter#latest', as: 'latest_twitter'

  get 'entities/:id/fan' => 'entities#fan', as: 'fan'

  resources :sessions, only: [:new, :create, :destroy]
end

app/models/entity.rb
class Entity < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/favorite_location.rb
class FavoriteLocation < ActiveRecord::Base
	has_and_belongs_to_many :users
end 

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, uniqueness: true, presence: true
  validates :password_hash, presence: true

  has_and_belongs_to_many :entities
  has_many :favorite_locations

  def password=(new_password)
  	write_attribute(
  		:password_hash, hash_password(new_password)
  	)
  end

  def authenticated_with?(password)
    read_attribute(:password_hash) == hash_password(password)
  end

  def self.authenticate(options = {})
  	params = options.merge(
  		'password_hash' =>  hash_password(options['password'])
  	)

  	params.delete('password')
  	User.where(params).first
  end

  def self.hash_password(password)
    Digest::MD5.hexdigest(password)
  end

  def hash_password(password)
    self.class.hash_password(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  	before_action :set_current_user
	private

	def set_current_user
		if session[:user_id]
			@current_user = User.find(session[:user_id])
		end
	end

end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
	def index
		@entities = Entity.all
	end

  def show
    @entity = Entity.find(params[:id])
  end

  def tickets
  	@entity = Entity.find(params[:id])
	end

  def fan
    @entity = Entity.find(params[:id])
  end

	def rides
		@entity = Entity.find(params[:id])
	end

end

app/controllers/entities_users_controller.rb
class EntitiesUsersController < ApplicationController
	respond_to :json

	def create
		user = User.find(entities_users_params[:user_id])
		entity = Entity.find(entities_users_params[:entity_id])

		unless user.entities.include?(entity)
			user.entities << entity
		end

		respond_to do |format|
			format.json { render json: {} }
		end
	end

	private

	def entities_users_params
		params.permit(:user_id, :entity_id)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if @current_user
      redirect_to user_entities_path(@current_user)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		if u = User.authenticate(user_params)
			session[:user_id] = u.id
			redirect_to(user_entities_path(u), notice: "Logged in!")
		else
			redirect_to(new_session_path, alert: "Invalid credentials")
		end
	end

	def destroy
		session.delete(:user_id)
		redirect_to(root_path, notice: "Logged out")
	end

	private

	def user_params
		params.require(:user).permit(:username, :password)
	end
end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController
  CLIENT = Twitter::REST::Client.new do |config|
    config.consumer_key        = ENV["TWITTER_CONSUMER_KEY"]
    config.consumer_secret     = ENV["TWITTER_CONSUMER_SECRET"]
    config.access_token        = ENV["TWITTER_ACCESS_TOKEN"]
    config.access_token_secret = ENV["TWITTER_ACCESS_SECRET"]
  end

  def latest
    tweets = CLIENT.user_timeline(params[:account], count: 1)

    respond_to do |format|
      format.json { render json: { ids: tweets.map(&:id) } }
    end
  end
end

app/controllers/users/entities_controller.rb
class Users::EntitiesController < ApplicationController
	def index
		@entities = User.find(params[:user_id]).entities
	end

	def create
		user = User.find(entities_users_params[:user_id])
		entity = Entity.find(entities_users_params[:id])

		unless user.entities.include?(entity)
			user.entities << entity
		end

		respond_to do |format|
			format.json { render json: {} }
		end
	end

	private

	def entities_users_params
		params.permit(:user_id, :id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	end

	def create
		user = User
			.where(username: user_params[:username])
			.first_or_initialize(user_params)

		if user.persisted?
			if user.authenticated_with?(user_params[:password])
				# if user already exists with same password, log them in
				session[:user_id] = user.id
				redirect_to(user_entities_path(user), notice: "Logged you in!")
				return
			end
		elsif user.save
			# if save succeeds, log them in
			session[:user_id] = user.id
			redirect_to(entities_path, notice: "Signed you up!")
			return
		end

		# if user already exists (or something else goes wrong),
		# display error message
		redirect_to(new_user_path, alert: "Invalid credentials")
	end

	private

	def user_params
		params.require(:user).permit(:username, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entities/fan.html.erb
<div class='entities fan row-fluid'>
  <%= render(partial: 'entities/shared/entity', locals: { entity: @entity, follow: false }) %>
  <%= image_tag('fan.gif') %>
</div>

app/views/entities/index.html.erb
<div class='entities index row-fluid'>
  <div class='col-xs-12'>
    <h4>What are you interested in?</h4>

    <% @entities.each do |entity| %>
      <%= render(partial: "entities/shared/entity", locals: { entity: entity, follow: true }) %>
    <% end %>

    <%= link_to('Done!', user_entities_path(@current_user), class: 'btn btn-default done-btn') %>
  </div>
</div>

app/views/entities/rides.html.erb
<div class='entities show row-fluid'>
  <%= render(partial: 'entities/shared/entity', locals: { entity: @entity, follow: false }) %> 
  <div class='buttons'>

		<button>
		Get a Ride!
		</button>

		<button>
		Pay your driver!
		</button>

		<%= image_tag("MastercardMoneySend.jpg", height: "75px", width: "112px") %>

	</div>
</div>

app/views/entities/shared/_entity.html.erb
<div class="entity" data-entity-id="<%= entity.id %>">
	<div class="logo">
		<img src="<%= image_path(entity.logo_path) %>"/>
	</div>
	<div class="info">
		<div class='category'><%= entity.category %></div>
		<div class='entity-name'><%= entity.name %></div>
	</div>
  <% if follow %>
    <button class='follow-btn btn btn-default'>Follow</button>
  <% end %>
</div>

app/views/entities/show.html.erb
<div class='entities show row-fluid'>
  <%= render(partial: 'entities/shared/entity', locals: { entity: @entity, follow: false }) %>
  <div class='tabs'>
    <div class='tab tab-read-it separator'>Read It</div>
    <div class='tab tab-live-it active'>Live it</div>
  </div>
  <div class='tab-contents read-it-contents inactive'>
    <div class='tweet tweet0'></div>
    <div class='score'>
      <div class='team'>
        <div class='team-logo cubs'></div>
        <div class='team-info'>
          <span class='city'>Chicago</span><br/>
          <span class='team-name'>Cubs</span>
        </div>
        <div class='team-score'>3</div>
      </div>

      <div class='team'>
        <div class='team-logo cardinals'></div>
        <div class='team-info'>
          <span class='city'>St. Louis</span><br/>
          <span class='team-name'>Cardinals</span>
        </div>
        <div class='team-score'>27</div>
      </div>
    </div>
    <div class='tweet tweet1'></div>
    <div class='tweet tweet2'></div>
  </div>
  <div class='tab-contents live-it-contents'>
    <%= link_to(rides_path) do %>
      <div class='bar'>Rides</div>
    <% end %>
    <%= link_to(tickets_path) do %>
      <div class='bar'>Tickets</div>
    <% end %>
    <div class='bar'>Competitions</div>
    <div class='bar'>Store</div>
    <div class='bar'>Auctions</div>
    <%= link_to(fan_path) do %>
      <div class='bar'>Ultimate Fan Experience</div>
    <% end %>
  </div>
</div>

app/views/entities/tickets.html.erb
<div class='entities show row-fluid'>
  <%= render(partial: 'entities/shared/entity', locals: { entity: @entity, follow: false }) %> 
  <div class='event_div'>
  	<div class='event_title'>
  	<h4>This Week:</h4>
  	<h5>Cardinals vs. Cubs @ Busch Stadium</h5>
  </div>
  <script type="text/javascript"
        src="https://www.simplify.com/commerce/simplify.pay.js"></script>
        <script type="text/javascript" src="https://www.simplify.com/commerce/v1/simplify.js"></script>
<button class='get_tickets_btn' data-sc-key="sbpb_NjM0YjI2OGItZGUxOC00OWYwLTg1ZWMtODk4NjQ2MGVmNzQz"
        data-name="Cardinals Tickets"
        data-description="Thursday October 15 @ 3:30pm \nBusch Stadium"
        data-reference="99999"
        data-amount="39999"
        data-color="#38A4DD"
        data-masterpass="true"
        ><span style="font-size: small !important;">Buy Now</span>
</button>
</div>

  </div>

app/views/home/index.html.erb
<div class='home index row-fluid'>
  <div class='col-xs-12'>
    <div class='logo'></div>
    <div class='logotype'></div>

    <div class='buttons'>
      <%= link_to(new_session_path) do %>
        <button class='btn btn-default'>Log In</button>
      <% end %>

      <%= link_to(new_user_path) do %>
        <button class='btn btn-default'>Sign Up</button>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fanfare</title>
    <link rel="apple-touch-startup-image" href="../../../images/splash-screen.png" />
    <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1,maximum-scale=1,user-scalable=yes,scrollbars=no" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'https://platform.twitter.com/widgets.js' %>
    <%= csrf_meta_tags %>
  </head>

  <body <%= @current_user ? "data-user-id=\"#{@current_user.id}\"".html_safe : "" %>>
    <div class='container-fluid'>
      <% if flash[:alert] || flash[:notice] %>
        <div class='flash'>
          <% if flash[:alert] %>
          	<p style="color: #BA0F0F"><%= flash[:alert] %></p>
          <% end %>
          <% if flash[:notice] %>
          	<p style="color: #319416"><%= flash[:notice] %></p>
          <% end %>
        </div>
      <% end %>

      <div class="top-nav">
        <% if @current_user %>
          <p class='user'>Logged in as <%= @current_user.username %></p>
          <p class='button'><%= link_to("Log Out", session_path(id: @current_user.id), method: 'DELETE') %></p>
        <% else %>
          <p class='button'><%= link_to("Log In", new_session_path) %></p>
        <% end %>
        <span class="octicon octicon-search"></span>
      </div>

      <%= yield %>

    </div>
  </body>
</html>

app/views/users/entities/index.html.erb
<div class='entities index row-fluid'>
  <div class='col-xs-12'>
    <h4>You're Following:</h4>
    <% @entities.each do |entity| %>
      <%= link_to(entity_path(entity)) do %>
        <%= render(partial: "entities/shared/entity", locals: { entity: entity, follow: false }) %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class='users new row-fluid'>
  <div class='col-xs-12'>
    <div class='logo'></div>
    <div class='logotype'></div>

    <div class='fields'>
      <%= form_for :user, as: 'POST', url:users_path do |f| %>
        <div class='input-group center-block'>
          <%= f.text_field :username, class: 'form-control', placeholder: 'Username' %>
          <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
          <%= f.submit 'Sign-up', class: 'btn btn-default' %>
        </div>
      <% end %>
    </div>
  </div>
</div>